version: '3.7'

services:
  postgres:
      image: bitnami/postgresql:latest
      ports:
        - '3306:3306'
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=vibrante
      volumes:
        - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: